"""Smoke test for the COMPOSITIONAL-GENERALIZATION probe (turns the I6 depth NULL into a
real probe by forcing the DEEP PC hierarchy — not the grid HEAD — to do the work).

The probe: inputs are generated by TWO independent latent factors (f1, f2). The observation
is a fixed COMPOSITIONAL embedding (concat of a per-f1 part and a per-f2 part). We train,
with local plasticity + Langevin noise, on a SUBSET of (f1,f2) combinations, holding some out.
At test we CLAMP the f1-part of x[0], leave the f2-part FREE, settle the PC hierarchy noise-free
(T=0), and read the completed f2-part. A model that FACTORED f1/f2 into the hierarchy can
complete held-out combos; a pure memorizer cannot.

These assertions only check ROBUSTLY-TRUE things: generator validity, finite/in-range outputs,
shape contracts, and that the noise-free completion runner is deterministic. They DO NOT assert
"depth helps" — whether it does is the empirical question the run script answers honestly.
"""
import numpy as np
from cerebrum.config import CerebrumConfig
from benchmarks.tasks.compositional import (
    CompositionalTask, run_pc_completion, run_flat_memorizer, run_backprop_mlp,
)


def test_task_factored_embedding_is_compositional_and_deterministic():
    task = CompositionalTask(A=3, B=3, part_dim=6, seed=0)
    # embedding splits cleanly into an f1-part and an f2-part of the declared widths
    e = task.embed(1, 2)
    assert e.shape == (task.obs_dim,)
    assert task.obs_dim == task.f1_dim + task.f2_dim
    # the f1-part depends ONLY on f1, the f2-part ONLY on f2 (genuine factorization possible)
    assert np.array_equal(task.embed(1, 0)[task.f1_slice], task.embed(1, 2)[task.f1_slice])
    assert np.array_equal(task.embed(0, 2)[task.f2_slice], task.embed(1, 2)[task.f2_slice])
    # deterministic
    assert np.array_equal(task.embed(2, 1), task.embed(2, 1))


def test_train_holdout_split_is_disjoint_and_covers_factors():
    task = CompositionalTask(A=3, B=3, part_dim=6, seed=1)
    train, held = task.train_combos, task.heldout_combos
    assert len(held) > 0 and len(train) > 0
    assert set(train).isdisjoint(set(held))
    # every factor value that appears in a held-out combo must have been SEEN in training in
    # some OTHER combo (otherwise completion is impossible even in principle -> not a fair probe)
    seen_f1 = {f1 for (f1, f2) in train}
    seen_f2 = {f2 for (f1, f2) in train}
    for (f1, f2) in held:
        assert f1 in seen_f1 and f2 in seen_f2


def test_pc_completion_runner_finite_and_in_range():
    task = CompositionalTask(A=3, B=3, part_dim=6, seed=2)
    cfg = CerebrumConfig(dims=(task.obs_dim, 16), n_settle=10, seed=0)
    res = run_pc_completion(task, cfg, passes=10)
    assert np.isfinite(res["acc_heldout"]) and 0.0 <= res["acc_heldout"] <= 1.0
    assert np.isfinite(res["acc_train"]) and 0.0 <= res["acc_train"] <= 1.0


def test_pc_completion_is_deterministic_readout():
    # the T=0 noise-free completion measurement must be a pure function of the learned weights
    task = CompositionalTask(A=3, B=3, part_dim=6, seed=3)
    cfg = CerebrumConfig(dims=(task.obs_dim, 16, 16), n_settle=8, seed=1)
    r1 = run_pc_completion(task, cfg, passes=8)
    r2 = run_pc_completion(task, cfg, passes=8)
    assert abs(r1["acc_heldout"] - r2["acc_heldout"]) < 1e-9
    assert abs(r1["acc_train"] - r2["acc_train"]) < 1e-9


def test_depth_variants_all_run():
    task = CompositionalTask(A=3, B=3, part_dim=6, seed=4)
    for dims in [(task.obs_dim, 16), (task.obs_dim, 16, 16), (task.obs_dim, 16, 16, 16)]:
        cfg = CerebrumConfig(dims=dims, n_settle=8, seed=0)
        res = run_pc_completion(task, cfg, passes=6)
        assert np.isfinite(res["acc_heldout"]) and 0.0 <= res["acc_heldout"] <= 1.0


def test_baselines_finite_and_in_range():
    task = CompositionalTask(A=3, B=3, part_dim=6, seed=5)
    mem = run_flat_memorizer(task)
    mlp = run_backprop_mlp(task, epochs=50, seed=0)
    assert np.isfinite(mem) and 0.0 <= mem <= 1.0
    assert np.isfinite(mlp) and 0.0 <= mlp <= 1.0
