import numpy as np

class KinematicChain:
    """Mathematical multi-joint serial manipulator simulator (robotic arm).
    Uses Jacobian Transpose method for Inverse Kinematics (IK).
    """
    def __init__(self, link_lengths):
        self.lengths = np.array(link_lengths, dtype=float)
        self.dof = len(link_lengths)
        self.angles = np.zeros(self.dof, dtype=float)
        
    def forward_kinematics(self, angles=None):
        """Compute 2D coordinates of all joints and end-effector.
        Returns array of coordinates: [[x0, y0], [x1, y1], ..., [x_ee, y_ee]]
        """
        if angles is None:
            angles = self.angles
            
        coords = np.zeros((self.dof + 1, 2))
        current_x = 0.0
        current_y = 0.0
        current_angle = 0.0
        
        coords[0] = [current_x, current_y]
        
        for i in range(self.dof):
            current_angle += angles[i]
            current_x += self.lengths[i] * np.cos(current_angle)
            current_y += self.lengths[i] * np.sin(current_angle)
            coords[i+1] = [current_x, current_y]
            
        return coords

    def get_jacobian(self):
        """Compute the geometric Jacobian matrix J for the end-effector in 2D.
        J is a 2 x DoF matrix.
        """
        coords = self.forward_kinematics()
        ee = coords[-1]
        J = np.zeros((2, self.dof))
        
        current_angle = 0.0
        for i in range(self.dof):
            current_angle += self.angles[i]
            # Vector from joint i to end-effector
            r = ee - coords[i]
            # J_i = z_axis x r_i = [-r_y, r_x]
            J[0, i] = -r[1]
            J[1, i] = r[0]
            
        return J

    def inverse_kinematics_step(self, target_pos, step_size=0.05):
        """One step of Jacobian Transpose IK to track a 3D/2D end-effector target.
        dTheta = J^T * error
        """
        coords = self.forward_kinematics()
        ee = coords[-1]
        error = target_pos - ee
        
        error_norm = np.linalg.norm(error)
        if error_norm < 1e-4:
            return error_norm, error
            
        J = self.get_jacobian()
        # d_theta = J_T * error
        d_theta = J.T @ error
        
        # Scale step to avoid joint coordinate explosion
        d_theta_norm = np.linalg.norm(d_theta)
        if d_theta_norm > 0.1:
            d_theta = (d_theta / d_theta_norm) * 0.1
            
        self.angles += step_size * d_theta
        # Apply physical joint limits
        self.angles = np.clip(self.angles, -np.pi, np.pi)
        
        return error_norm, error


class BipedBackflipDynamics:
    """2D rigid body dynamics simulation in the sagittal plane for biped backflips.
    Tracks COM (x, y), orientation theta, and angular velocity omega.
    Simulates takeoff force, flight rotation, and ground landing contact forces.
    """
    def __init__(self, mass=80.0, inertia=15.0):
        self.m = mass
        self.I = inertia
        self.g = 9.81
        
        # State: [x, y, vx, vy, theta, omega]
        self.state = np.zeros(6, dtype=float)
        self.ground_y = 0.0
        self.in_flight = False
        
        # Joint states for rendering [hip, knee, ankle]
        self.joints = np.array([0.2, -0.4, 0.2]) 
        self.torque = np.zeros(3)
        
    def reset(self, initial_y=0.9):
        # Position biped upright at height y
        self.state = np.array([0.0, initial_y, 0.0, 0.0, 0.0, 0.0])
        self.in_flight = False
        self.joints = np.array([0.2, -0.4, 0.2])
        self.torque = np.zeros(3)

    def step(self, action_torque, dt=0.01):
        """Simulate single step of forward dynamics using Euler integration.
        action_torque: [hip_torque, knee_torque, ankle_torque]
        """
        x, y, vx, vy, theta, omega = self.state
        
        # Active control torques
        self.torque = np.clip(action_torque, -300.0, 300.0) # max torque limit
        
        # Gravity force
        F_gravity = np.array([0.0, -self.m * self.g])
        F_contact = np.zeros(2)
        T_contact = 0.0
        
        # Ground reaction force (Spring-damper contact model)
        # Biped height is roughly 0.9m. Contact triggers when feet touch ground
        foot_y = y - 0.9 * np.cos(theta)
        
        if foot_y <= self.ground_y:
            self.in_flight = False
            # Penetration depth
            pen = self.ground_y - foot_y
            
            # Normal spring-damper force (vertical)
            F_n = 25000.0 * pen - 800.0 * vy
            F_n = max(0.0, F_n)
            
            # Friction force (horizontal)
            F_f = -1500.0 * vx - 100.0 * np.sign(vx)
            
            F_contact = np.array([F_f, F_n])
            
            # Torque generated by contact offset
            foot_x = x - 0.9 * np.sin(theta)
            r = np.array([foot_x - x, foot_y - y])
            T_contact = r[0] * F_n - r[1] * F_f
        else:
            self.in_flight = True
            
        # Equations of motion:
        # Total force = Gravity + Contact
        F_total = F_gravity + F_contact
        accel = F_total / self.m
        
        # Angular acceleration:
        # Net internal joint torques + external contact torques
        # Internal joint action can accelerate core orientation if landing
        # Hip torque reacts on body inertia
        T_joints = self.torque[0] + self.torque[1] * 0.5
        T_net = T_contact + T_joints
        alpha = T_net / self.I
        
        # Integrate position
        vx += accel[0] * dt
        vy += accel[1] * dt
        x += vx * dt
        y += vy * dt
        
        # Integrate orientation
        omega += alpha * dt
        theta += omega * dt
        
        self.state = np.array([x, y, vx, vy, theta, omega])
        
        # Update joint angles based on dynamic state
        # Hip flexes to tuck during backflip
        if self.in_flight:
            # Flight Phase: Tucking legs
            target_hip = 1.8 # High flexion
            target_knee = -2.2 # Deep tuck
            target_ankle = 0.4
        else:
            # Landing/Squat Phase: Absorbing impact
            target_hip = 0.5 + 0.005 * self.torque[0]
            target_knee = -1.0 + 0.005 * self.torque[1]
            target_ankle = 0.5 + 0.005 * self.torque[2]
            
        # Smooth joints update (simulating motor inertia)
        self.joints += 0.15 * (np.array([target_hip, target_knee, target_ankle]) - self.joints)
        
        # Return landing impact info
        impact_force = F_contact[1] if not self.in_flight else 0.0
        return impact_force


class TrayBalanceDynamics:
    """Tray balancing physics simulator for Figure 01.
    Computes body accelerations, tray orientation (tilt angle), and the
    balancing torque required from waist/wrist joints to keep liquid/objects flat.
    """
    def __init__(self):
        self.body_sway = 0.0
        self.body_vel = 0.0
        self.tray_angle = 0.0
        self.tray_vel = 0.0
        self.target_angle = 0.0
        self.fluid_slosh = 0.0
        
    def step(self, control_torque, dt=0.02):
        """Simulate sway disturbance and calculate active stabilization.
        control_torque: stabilizing torque applied by arm joints.
        """
        # 1. Simulate external disturbance (body walking sway)
        # Walking frequency is roughly 1.5 Hz
        t = time_step = getattr(self, '_time_step', 0)
        self._time_step = t + 1
        
        sway_accel = 1.2 * np.sin(t * 0.1) + np.random.normal(0, 0.1)
        self.body_vel += sway_accel * dt
        self.body_sway += self.body_vel * dt
        
        # 2. Tray Dynamics:
        # Tilt angle is affected by body sway acceleration (inertial force)
        # plus the active wrist control torque
        # Inertia of tray is small (~0.5 kg m^2)
        I_tray = 0.4
        
        # Inertial disturbance torque: -m * a * h * cos(theta)
        T_inertial = -1.5 * sway_accel * 0.3 * np.cos(self.tray_angle)
        
        # Net torque includes control torque stabilizer
        T_net = T_inertial + control_torque
        
        tray_alpha = T_net / I_tray
        self.tray_vel += tray_alpha * dt
        self.tray_angle += self.tray_vel * dt
        
        # 3. Simulate fluid slosh (energy tracking indicator)
        # Slosh is driven by angular velocity and angular acceleration
        self.fluid_slosh = 0.9 * self.fluid_slosh + 0.1 * (abs(self.tray_vel) * 2.0 + abs(tray_alpha) * 0.2)
        
        # Cap angles to represent drop failure
        self.tray_angle = np.clip(self.tray_angle, -np.pi/3, np.pi/3)
        
        return self.tray_angle, self.fluid_slosh


class BaseLocomotionSimulator:
    """Differential drive wheeled robot navigation simulator.
    Converts motor commands to linear and angular velocities,
    accounting for wheel slip, friction, and integration errors.
    """
    def __init__(self):
        self.x = 0.0
        self.y = 0.0
        self.theta = 0.0
        
        self.left_wheel_speed = 0.0
        self.right_wheel_speed = 0.0
        self.wheel_base = 0.4
        self.wheel_radius = 0.08
        self.slip_pct = 0.03 # 3% default wheel slip
        
    def reset(self, x=0.0, y=0.0, theta=0.0):
        self.x = x
        self.y = y
        self.theta = theta
        self.left_wheel_speed = 0.0
        self.right_wheel_speed = 0.0
        
    def step(self, left_volt, right_volt, dt=0.05):
        """Standard differential drive equations with noise and slip."""
        # Motor model (simple first-order voltage to wheel speed)
        # volts scale wheels speed up to 15 rad/s
        target_l = left_volt * 1.5
        target_r = right_volt * 1.5
        
        # Add wheel slippage (random reduction in traction)
        slip_l = 1.0 - (self.slip_pct + np.random.uniform(0, 0.04))
        slip_r = 1.0 - (self.slip_pct + np.random.uniform(0, 0.04))
        
        self.left_wheel_speed += 0.2 * (target_l * slip_l - self.left_wheel_speed)
        self.right_wheel_speed += 0.2 * (target_r * slip_r - self.right_wheel_speed)
        
        # Convert wheel angular velocities to linear base velocities
        v_l = self.left_wheel_speed * self.wheel_radius
        v_r = self.right_wheel_speed * self.wheel_radius
        
        # Forward Kinematics for Differential Drive
        v = (v_l + v_r) / 2.0
        omega = (v_r - v_l) / self.wheel_base
        
        # Integrate pose
        self.x += v * np.cos(self.theta) * dt
        self.y += v * np.sin(self.theta) * dt
        self.theta += omega * dt
        
        # Keep theta in [-pi, pi]
        self.theta = (self.theta + np.pi) % (2 * np.pi) - np.pi
        
        # Return odometry readings (with sensor noise)
        odom_v = v + np.random.normal(0, 0.01)
        odom_w = omega + np.random.normal(0, 0.005)
        
        return self.x, self.y, self.theta, odom_v, odom_w
